" - - - Vim gui configuration

" font
set guifont=Monaco:h24

" tabbar on, scrollbar off
set guioptions=em

" cursor
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver10-Cursor
set guicursor+=a:blinkon0
hi Cursor guifg=bg guibg=DarkGrey

" edit gvimrc
nnoremap <Leader>+ :tabedit<space>~/.gvimrc<cr>

