" - - - Vim Configuration

" - Colors

hi TabLine cterm=italic ctermfg=8 ctermbg=0
hi TabLineFill cterm=none ctermfg=8 ctermbg=none
hi TabLineSel cterm=italic ctermfg=6 ctermbg=0
hi Title cterm=bold ctermfg=none ctermbg=none
hi StatusLine cterm=italic ctermfg=6 ctermbg=none
hi StatusLineNC cterm=italic ctermfg=8 ctermbg=none
hi VertSplit cterm=none ctermfg=6 ctermbg=none
hi WildMenu cterm=italic ctermfg=8 ctermbg=0
hi ModeMsg cterm=bold ctermfg=6 ctermbg=none
hi ErrorMsg cterm=italic ctermfg=9 ctermbg=none
hi LineNr cterm=none ctermfg=15 ctermbg=none
hi LineNrAbove cterm=none ctermfg=8 ctermbg=none
hi LineNrBelow cterm=none ctermfg=8 ctermbg=none
hi CursorLine cterm=none ctermfg=none ctermbg=0
hi CursorLineNr cterm=none ctermfg=15 ctermbg=none
hi Folded cterm=none ctermfg=14 ctermbg=0
hi Operator cterm=none ctermfg=11
hi Identifier cterm=none
hi Function cterm=none ctermfg=14
hi Repeat cterm=none ctermfg=11

" - Options

set autochdir         " Working directory matches current file
set autoindent        " New line indents to match previous line
set background=dark   " Ensure a dark background
set belloff=all       " Be quiet
set cm=blowfish2      " Use best available encryption
set ignorecase        " Search is case-insensitive
set incsearch         " Search begins while typing query
set laststatus=0      " Statusline only between splits
set nocompatible      " Modernity
set noruler           " Disable ruler
set noshowcmd         " Do not show keystrokes
set noshowmode        " Do not show curent mode
set number            " Line numbers
set relativenumber    " Relative line numbers 
set showtabline=2     " Tabline always
set smartcase         " if query is all lower case
set splitbelow        " Horizontal splits open below current
set splitright        " Vertical splits open to the right of current
set ttimeoutlen=5     " Reduced key delay
set undofile          " Preserve undo tree accross file closures
set wildmenu          " Menu for command completions
syntax on             " Syntax coloring

" Cursor
let &t_SI.="\e[6 q"   " Line cursor in insert mode
let &t_EI.="\e[2 q"   " Block cursor in other modes

" Indentation
set tabstop=8
set softtabstop=8
set shiftwidth=8
set noexpandtab
filetype indent on

" Backup, swap, and undo file locations
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" - Keymaps

" Leader
let mapleader=' '

" Fast write / quit
"nnoremap <cr> :w<cr>
nnoremap <bs> :q<cr>

" Buffer navigation
nnoremap <leader>n :bn<cr>
nnoremap <leader>p :bp<cr>
nnoremap <leader>e :edit<space>
nnoremap <leader>d :bd<cr>

" Viewport navigation
nnoremap <leader>w <c-w>w
nnoremap <leader><space> <c-w>w
nnoremap <leader>x :sp<space>
nnoremap <leader>v :vsp<space>

" Tab navigation
nnoremap <tab> :tabn<cr>
nnoremap <s-tab> :tabp<cr>
nnoremap <leader><tab> :tabedit<space>
nnoremap <leader>t <c-w>T

" Substitution
nnoremap <leader>s :s//g<left><left>
nnoremap <leader>S :%s//g<left><left>

" o / O
nnoremap 2o o<Esc>o
nnoremap 2O O<Esc>O
nnoremap 1o o<Esc>o<Esc>o<Esc>ki
nnoremap 1O O<Esc>O<Esc>O<Esc>ji

" Yank to end of line
nnoremap Y y$

" Edit vimrc
nnoremap <leader>= :tabedit<space>~/.vim/vimrc<cr>

" Visual line shifts
vnoremap H <gv
vnoremap J :m<space>'>+1<cr>gv=gv
vnoremap K :m<space>'<-2<cr>gv=gv
vnoremap L >gv

" - Plugins

filetype plugin on                " Enable plugins
runtime ftplugin/man.vim          " Source man.vim
let g:limelight_conceal_ctermfg=7 " Limelight dimmed color

" - Autocommands

" Disable automatic commenting
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

